# Generated by Django 6.0.8 on 2026-08-19 15:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Дата создания"),
        ),
        migrations.AddField(
            model_name="habit",
            name="last_notification_date",
            field=models.DateField(blank=True, null=True, verbose_name="Последняя дата напоминания"),
        ),
    ]
